export type DbConfig = { host: string; port: number; user: string; password: string; database: string };
export type PublicDbConfig = Omit<DbConfig, 'password'> & { hasPassword: boolean };
export type IpcResult<T> = { ok: true; data: T } | { ok: false; error: string };
export type StartupState = { configured: boolean; databaseReady: boolean; needsAdmin: boolean; message?: string; detail?: string };
export type UserRole = 'ADMIN' | 'CAJERO' | 'MESERO' | 'COCINA';
export type OrderStatus = 'PENDIENTE' | 'EN_COCINA' | 'LISTO' | 'PAGADO' | 'CANCELADO';
export type CashMovementType = 'VENTA' | 'GASTO' | 'APERTURA' | 'RETIRO' | 'DEPOSITO';
export type PaymentMethod = 'EFECTIVO' | 'TARJETA' | 'YAPE_PLIN';
export type LoginRequest = { pin: string };
export type CreateAdminRequest = { nombre: string; pin: string };
export type UserSession = { id: string; nombre: string; rol: UserRole };
export type UserSummary = UserSession & { activo: boolean };
export type UserCreateRequest = { actorId: string; nombre: string; pin: string; rol: UserRole };
export type UserUpdateRequest = { actorId: string; id: string; nombre?: string; rol?: UserRole; activo?: boolean; pin?: string };
export type ProductVariantInput = { id?: string; nombre: string; precio: string; stock?: number };
export type ProductInput = { actorId?: string; nombre: string; descripcion?: string; categoria: string; activo?: boolean; variants?: ProductVariantInput[] };
export type ProductUpdateRequest = { actorId?: string; id: string; nombre?: string; descripcion?: string; categoria?: string; activo?: boolean; variants?: ProductVariantInput[] };
export type ProductListItem = { id: string; codigo: string; nombre: string; descripcion?: string | null; categoria: string; activo: boolean; variants: Array<{ id: string; sku: string; nombre: string; precio: string; stock: number }> };
export type InventoryItem = { variantId: string; productId: string; sku: string; producto: string; variante: string; precio: string; stock: number; estado: 'normal' | 'stock_bajo' | 'sin_stock' };
export type InventoryAdjustRequest = { variantId: string; delta: number; userId: string; reason: string };
export type CreateOrderRequest = { mesa?: string; userId: string; items: Array<{ variantId: string; cantidad: number }> };
export type PayOrderRequest = { orderId: string; userId: string; paymentMethod: PaymentMethod; receivedAmount?: string };
export type UpdateOrderStatusRequest = { orderId: string; estado: OrderStatus; userId: string; cashRegisterId?: string; paymentMethod?: PaymentMethod };
export type OrderListItem = { id: string; mesa?: string | null; estado: OrderStatus; userId: string; userName: string; createdAt: string; total: string; paymentMethod?: PaymentMethod | null; items: Array<{ id: string; variantId: string; producto: string; variante: string; cantidad: number; precioUnitario: string; subtotal: string }> };
export type CashOpenRequest = { userId: string; initialAmount: string };
export type CashCloseRequest = { cashRegisterId: string; userId: string };
export type CashMovementRequest = { cashRegisterId?: string; userId: string; tipo: CashMovementType; monto: string; detalle?: Record<string, unknown> };
export type CashRegisterSummary = { id: string; openedBy: string; openedByName: string; initialAmount: string; status: 'ABIERTA' | 'CERRADA'; openedAt: string; closedAt?: string | null; balance: string; movements: Array<{ id: string; tipo: CashMovementType; monto: string; createdAt: string }> };
export type DashboardSummary = { salesToday: string; ordersToday: number; productsCount: number; lowStockCount: number; cashStatus: 'ABIERTA' | 'CERRADA' | 'SIN_CAJA'; cashBalance: string; latestSales: Array<{ time: string; orderId: string; userName: string; total: string; paymentMethod?: PaymentMethod | null }>; currentUser: UserSession; database: { connected: boolean; message: string } };
export type AuditLogItem = { id: string; userName: string; accion: string; detalle: unknown; createdAt: string };
export type Api = {
  config: { exists(): Promise<IpcResult<boolean>>; save(config: DbConfig): Promise<IpcResult<StartupState>>; startupState(): Promise<IpcResult<StartupState>>; getPublic(): Promise<IpcResult<PublicDbConfig | null>>; test(): Promise<IpcResult<{ connected: boolean; message: string }>> };
  auth: { login(request: LoginRequest): Promise<IpcResult<UserSession>>; logout(userId?: string): Promise<IpcResult<boolean>>; createInitialAdmin(request: CreateAdminRequest): Promise<IpcResult<UserSession>> };
  dashboard: { summary(user: UserSession): Promise<IpcResult<DashboardSummary>> };
  users: { list(actorId: string): Promise<IpcResult<UserSummary[]>>; create(request: UserCreateRequest): Promise<IpcResult<UserSummary>>; update(request: UserUpdateRequest): Promise<IpcResult<UserSummary>> };
  audit: { list(actorId: string): Promise<IpcResult<AuditLogItem[]>> };
  orders: { create(request: CreateOrderRequest): Promise<IpcResult<OrderListItem>>; pay(request: PayOrderRequest): Promise<IpcResult<OrderListItem>>; updateStatus(request: UpdateOrderStatusRequest): Promise<IpcResult<OrderListItem>>; list(user: UserSession): Promise<IpcResult<OrderListItem[]>>; getById(id: string): Promise<IpcResult<OrderListItem | null>> };
  inventory: { get(): Promise<IpcResult<InventoryItem[]>>; adjust(request: InventoryAdjustRequest): Promise<IpcResult<InventoryItem>> };
  cash: { current(): Promise<IpcResult<CashRegisterSummary | null>>; list(): Promise<IpcResult<CashRegisterSummary[]>>; open(request: CashOpenRequest): Promise<IpcResult<CashRegisterSummary>>; close(request: CashCloseRequest): Promise<IpcResult<CashRegisterSummary>>; registerMovement(request: CashMovementRequest): Promise<IpcResult<CashRegisterSummary>>; getBalance(cashRegisterId: string): Promise<IpcResult<string>> };
  products: { list(): Promise<IpcResult<ProductListItem[]>>; create(request: ProductInput): Promise<IpcResult<ProductListItem>>; update(request: ProductUpdateRequest): Promise<IpcResult<ProductListItem>> };
};
