import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api, missingPreloadApiMessage } from './lib/ipc-client';
import type { AuditLogItem, CashRegisterSummary, DashboardSummary, InventoryItem, OrderListItem, OrderStatus, PaymentMethod, ProductListItem, StartupState, UserRole, UserSession, UserSummary } from '../shared/ipc';

type ModuleKey = 'dashboard' | 'ventas' | 'pedidos' | 'productos' | 'inventario' | 'caja' | 'usuarios' | 'auditoria' | 'configuracion';
type Notice = { kind: 'ok' | 'error' | 'info'; text: string } | null;
const roles: UserRole[] = ['ADMIN', 'CAJERO', 'MESERO', 'COCINA'];
const statuses: OrderStatus[] = ['PENDIENTE', 'EN_COCINA', 'LISTO', 'PAGADO', 'CANCELADO'];
const money = (value: string | number) => `S/ ${Number(value || 0).toFixed(2)}`;

export default function App() {
  if (!window.api) return <PreloadDiagnostic />;
  const [startup, setStartup] = useState<StartupState | null>(null);
  const [message, setMessage] = useState('');
  const [user, setUser] = useState<UserSession | null>(null);
  useEffect(() => { void refreshStartup(setStartup, setMessage); }, []);
  if (startup === null) return <main className="p-8">Cargando...</main>;
  if (!startup.configured) return <ConfigScreen onDone={setStartup} setMessage={setMessage} message={message} />;
  if (!startup.databaseReady) return <DatabaseErrorScreen startup={startup} onRetry={setStartup} message={message} setMessage={setMessage} />;
  if (startup.needsAdmin) return <InitialAdminScreen onDone={() => setStartup({ ...startup, needsAdmin: false })} setMessage={setMessage} message={message} />;
  if (user) return <AuthenticatedApp user={user} onLogout={() => setUser(null)} />;
  return <LoginScreen onLogin={setUser} message={message} setMessage={setMessage} />;
}

async function refreshStartup(setStartup: (s: StartupState) => void, setMessage: (m: string) => void) {
  try {
    const r = await api.config.startupState();
    if (r.ok) setStartup(r.data); else { setMessage(r.error); setStartup({ configured: true, databaseReady: false, needsAdmin: false }); }
  } catch (error) {
    setMessage(error instanceof Error ? error.message : 'No se pudo consultar el estado inicial.');
    setStartup({ configured: true, databaseReady: false, needsAdmin: false });
  }
}

function PreloadDiagnostic() {
  return <main className="mx-auto mt-16 max-w-2xl rounded-2xl bg-amber-950 p-8 shadow-xl"><h1 className="text-2xl font-bold text-amber-100">API de Electron no disponible</h1><p className="mt-4 text-amber-100">{missingPreloadApiMessage}</p></main>;
}

function ConfigScreen({ onDone, message, setMessage }: { onDone: (state: StartupState) => void; message: string; setMessage: (m: string) => void }) {
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setMessage('Probando conexión y ejecutando migraciones...');
    const form = new FormData(event.currentTarget);
    const result = await api.config.save({ host: String(form.get('host')), port: Number(form.get('port')), user: String(form.get('user')), password: String(form.get('password')), database: String(form.get('database')) });
    if (result.ok) { setMessage(''); onDone(result.data); } else setMessage(result.error);
  }
  return <AuthCard title="Configurar PostgreSQL local"><p className="mt-2 text-slate-300">Se guardará en userData/config.json y se ejecutarán migraciones automáticamente.</p><form onSubmit={submit} className="mt-6 grid gap-4"><input name="host" defaultValue="localhost" className="input" placeholder="Host" /><input name="port" defaultValue="5432" type="number" className="input" placeholder="Puerto" /><input name="user" className="input" placeholder="Usuario" /><input name="password" type="password" className="input" placeholder="Password" /><input name="database" className="input" placeholder="Base de datos" />{message && <p className="text-red-300">{message}</p>}<button className="btn-primary">Guardar y migrar</button></form></AuthCard>;
}

function DatabaseErrorScreen({ startup, onRetry, message, setMessage }: { startup: StartupState; onRetry: (state: StartupState) => void; message: string; setMessage: (m: string) => void }) {
  async function retry() { setMessage('Reintentando conexión y migraciones...'); await refreshStartup(onRetry, setMessage); }
  return <AuthCard title="No se pudo inicializar PostgreSQL"><p className="mt-4 whitespace-pre-wrap rounded bg-slate-800 p-4 text-red-100">{startup.detail || startup.message || message}</p><button onClick={retry} className="btn-primary mt-6">Reintentar</button></AuthCard>;
}

function InitialAdminScreen({ onDone, message, setMessage }: { onDone: () => void; message: string; setMessage: (m: string) => void }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const result = await api.auth.createInitialAdmin({ nombre: String(form.get('nombre')), pin: String(form.get('pin')) }); if (result.ok) { setMessage('ADMIN inicial creado. Ingresa con el PIN configurado.'); onDone(); } else setMessage(result.error); }
  return <AuthCard title="Crear ADMIN inicial"><p className="mt-2 text-slate-300">Define el primer ADMIN sin usar un PIN hardcodeado.</p><form onSubmit={submit} className="mt-6 grid gap-4"><input name="nombre" className="input" placeholder="Nombre del ADMIN" /><input name="pin" type="password" className="input" placeholder="PIN (4 a 12 dígitos)" />{message && <p className="text-red-300">{message}</p>}<button className="btn-primary">Crear ADMIN</button></form></AuthCard>;
}

function LoginScreen({ onLogin, message, setMessage }: { onLogin: (user: UserSession) => void; message: string; setMessage: (m: string) => void }) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setIsSubmitting(true); setMessage(''); const form = event.currentTarget; const pin = String(new FormData(form).get('pin'));
    try { const result = await api.auth.login({ pin }); if (result.ok) { form.reset(); onLogin(result.data); } else setMessage(result.error); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo iniciar sesión.'); } finally { setIsSubmitting(false); }
  }
  return <AuthCard title="Life System POS"><p className="mt-2 text-slate-300">Login por PIN usando IPC seguro.</p><form onSubmit={submit} className="mt-6 grid gap-4"><input name="pin" type="password" className="input text-center text-2xl tracking-widest" placeholder="PIN" /><button disabled={isSubmitting} className="btn-primary disabled:opacity-60">{isSubmitting ? 'Ingresando...' : 'Ingresar'}</button></form>{message && <p className="mt-4 rounded bg-slate-800 p-3">{message}</p>}</AuthCard>;
}

function AuthCard({ title, children }: { title: string; children: React.ReactNode }) { return <main className="flex min-h-screen items-center justify-center p-8"><section className="w-full max-w-xl rounded-2xl bg-slate-900 p-8 shadow-xl"><h1 className="text-3xl font-bold">{title}</h1>{children}</section></main>; }

function AuthenticatedApp({ user, onLogout }: { user: UserSession; onLogout: () => void }) {
  const modules = allowedModules(user.rol);
  const [active, setActive] = useState<ModuleKey>('dashboard');
  const [db, setDb] = useState<{ connected: boolean; message: string }>({ connected: false, message: 'Verificando...' });
  const [notice, setNotice] = useState<Notice>(null);
  useEffect(() => { void checkDb(setDb); }, []);
  async function logout() { const result = await api.auth.logout(user.id); if (!result.ok) setNotice({ kind: 'error', text: result.error }); else onLogout(); }
  return <div className="min-h-screen bg-slate-950 text-slate-100 lg:flex"><aside className="border-b border-slate-800 bg-slate-900 p-4 lg:min-h-screen lg:w-64 lg:border-b-0 lg:border-r"><h2 className="text-xl font-bold">Life System POS</h2><nav className="mt-6 grid gap-2">{modules.map((m) => <button key={m} onClick={() => setActive(m)} className={`rounded-lg px-3 py-2 text-left ${active === m ? 'bg-blue-600' : 'bg-slate-800 hover:bg-slate-700'}`}>{moduleLabel(m)}</button>)}</nav></aside><section className="flex-1"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 bg-slate-900 px-6 py-4"><div><h1 className="text-2xl font-bold">{moduleLabel(active)}</h1><p className="text-sm text-slate-400">{user.nombre} · {user.rol}</p></div><div className="flex flex-wrap items-center gap-3"><span className={db.connected ? 'text-emerald-300' : 'text-red-300'}>● PostgreSQL {db.connected ? 'conectado' : 'desconectado'}</span><button onClick={() => void checkDb(setDb)} className="btn-muted">Probar conexión</button><button onClick={logout} className="btn-danger">Cerrar sesión</button></div></header><main className="p-4 lg:p-6">{notice && <NoticeBox notice={notice} onClose={() => setNotice(null)} />}{renderModule(active, user, setNotice, db, setDb)}</main></section></div>;
}

function renderModule(active: ModuleKey, user: UserSession, setNotice: (n: Notice) => void, db: { connected: boolean; message: string }, setDb: (d: { connected: boolean; message: string }) => void) {
  if (active === 'dashboard') return <Dashboard user={user} />;
  if (active === 'ventas') return <Sales user={user} setNotice={setNotice} />;
  if (active === 'pedidos') return <Orders user={user} setNotice={setNotice} />;
  if (active === 'productos') return <Products user={user} setNotice={setNotice} />;
  if (active === 'inventario') return <Inventory user={user} setNotice={setNotice} />;
  if (active === 'caja') return <Cash user={user} setNotice={setNotice} />;
  if (active === 'usuarios') return <Users user={user} setNotice={setNotice} />;
  if (active === 'auditoria') return <Audit user={user} />;
  return <Settings db={db} setDb={setDb} />;
}

function allowedModules(role: UserRole): ModuleKey[] { const all: ModuleKey[] = ['dashboard', 'ventas', 'pedidos', 'productos', 'inventario', 'caja', 'usuarios', 'auditoria', 'configuracion']; if (role === 'ADMIN') return all; if (role === 'CAJERO') return ['dashboard', 'ventas', 'pedidos', 'productos', 'inventario', 'caja', 'configuracion']; if (role === 'MESERO') return ['dashboard', 'ventas', 'pedidos', 'productos', 'configuracion']; return ['dashboard', 'pedidos', 'configuracion']; }
function moduleLabel(m: ModuleKey) { return ({ dashboard: 'Dashboard', ventas: 'Ventas', pedidos: 'Pedidos', productos: 'Productos', inventario: 'Inventario', caja: 'Caja', usuarios: 'Usuarios', auditoria: 'Auditoría', configuracion: 'Configuración' } as Record<ModuleKey, string>)[m]; }
async function checkDb(setDb: (d: { connected: boolean; message: string }) => void) { const r = await api.config.test(); setDb(r.ok ? r.data : { connected: false, message: r.error }); }
function NoticeBox({ notice, onClose }: { notice: NonNullable<Notice>; onClose: () => void }) { return <div className={`mb-4 rounded-lg p-3 ${notice.kind === 'error' ? 'bg-red-950 text-red-100' : notice.kind === 'ok' ? 'bg-emerald-950 text-emerald-100' : 'bg-blue-950 text-blue-100'}`}><button onClick={onClose} className="float-right">×</button>{notice.text}</div>; }

function Dashboard({ user }: { user: UserSession }) {
  const [data, setData] = useState<DashboardSummary | null>(null); const [error, setError] = useState('');
  useEffect(() => { api.dashboard.summary(user).then((r) => r.ok ? setData(r.data) : setError(r.error)).catch((e: unknown) => setError(String(e))); }, [user]);
  if (error) return <Panel title="Dashboard"><p className="text-red-300">{error}</p></Panel>; if (!data) return <Panel title="Dashboard">Cargando métricas...</Panel>;
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Metric title="Ventas del día" value={Number(data.salesToday) ? money(data.salesToday) : 'Sin ventas'} /><Metric title="Pedidos del día" value={data.ordersToday || 'Sin pedidos'} /><Metric title="Productos registrados" value={data.productsCount || 'Sin productos'} /><Metric title="Stock bajo" value={data.lowStockCount} /><Metric title="Caja" value={data.cashStatus} /><Metric title="Usuario" value={`${data.currentUser.nombre} (${data.currentUser.rol})`} /><Metric title="PostgreSQL" value={data.database.connected ? 'Conectado' : 'Desconectado'} /></div>;
}
function Metric({ title, value }: { title: string; value: React.ReactNode }) { return <div className="rounded-xl bg-slate-900 p-5 shadow"><p className="text-sm text-slate-400">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>; }

function Products({ user, setNotice }: { user: UserSession; setNotice: (n: Notice) => void }) {
  const [products, setProducts] = useState<ProductListItem[]>([]); const [edit, setEdit] = useState<ProductListItem | null>(null); const canEdit = user.rol === 'ADMIN';
  const load = async () => { const r = await api.products.list(); if (r.ok) setProducts(r.data); else setNotice({ kind: 'error', text: r.error }); };
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const payload = { actorId: user.id, nombre: String(f.get('nombre')), categoria: String(f.get('categoria')), variants: [{ id: edit?.variants[0]?.id, nombre: String(f.get('variante')), precio: String(f.get('precio')), stock: Number(f.get('stock') || 0) }] }; const r = edit ? await api.products.update({ ...payload, id: edit.id }) : await api.products.create(payload); if (r.ok) { setNotice({ kind: 'ok', text: 'Producto guardado correctamente' }); setEdit(null); event.currentTarget.reset(); await load(); } else setNotice({ kind: 'error', text: r.error }); }
  return <Panel title="Productos">{canEdit && <form onSubmit={submit} className="grid gap-3 rounded-xl bg-slate-800 p-4 md:grid-cols-3"><input name="nombre" defaultValue={edit?.nombre} className="input" placeholder="Producto" required /><input name="categoria" defaultValue={edit?.categoria} className="input" placeholder="Categoría" required /><input name="variante" defaultValue={edit?.variants[0]?.nombre} className="input" placeholder="Variante" required /><input name="precio" defaultValue={edit?.variants[0]?.precio} className="input" placeholder="Precio" type="number" step="0.01" required /><input name="stock" defaultValue={edit ? undefined : 0} className="input" placeholder="Stock inicial" type="number" min="0" /><button className="btn-primary">{edit ? 'Actualizar' : 'Crear producto'}</button></form>}<Table headers={['Nombre', 'Categoría', 'Variantes', 'Estado', '']} rows={products.map((p) => [p.nombre, p.categoria, p.variants.map((v) => `${v.nombre} · ${money(v.precio)} · stock ${v.stock}`).join('\n') || 'Sin variantes', p.variants.some((v) => v.stock <= 5) ? 'Stock bajo' : 'Activo', canEdit ? <button onClick={() => setEdit(p)} className="btn-muted">Editar</button> : ''])} /></Panel>;
}

function Inventory({ user, setNotice }: { user: UserSession; setNotice: (n: Notice) => void }) { const [items, setItems] = useState<InventoryItem[]>([]); const canEdit = ['ADMIN', 'CAJERO'].includes(user.rol); const load = async () => { const r = await api.inventory.get(); if (r.ok) setItems(r.data); else setNotice({ kind: 'error', text: r.error }); }; useEffect(() => { void load(); }, []); async function adjust(variantId: string, delta: number) { const r = await api.inventory.adjust({ variantId, delta, userId: user.id, reason: 'Ajuste manual desde POS' }); if (r.ok) { setNotice({ kind: 'ok', text: 'Stock actualizado correctamente' }); await load(); } else setNotice({ kind: 'error', text: r.error }); } return <Panel title="Inventario"><Table headers={['Producto', 'Variante', 'Precio', 'Stock actual', 'Ajuste']} rows={items.map((i) => [i.producto, i.variante, money(i.precio), i.stock, canEdit ? <InventoryAdjust onAdjust={(d) => void adjust(i.variantId, d)} /> : 'Solo lectura'])} /></Panel>; }
function InventoryAdjust({ onAdjust }: { onAdjust: (delta: number) => void }) { const [qty, setQty] = useState(1); return <div className="flex gap-2"><input value={qty} onChange={(e) => setQty(Number(e.target.value))} className="input w-20" type="number" min="1" /><button onClick={() => onAdjust(qty)} className="btn-muted">+</button><button onClick={() => onAdjust(-qty)} className="btn-danger">-</button></div>; }

function Sales({ user, setNotice }: { user: UserSession; setNotice: (n: Notice) => void }) { const [products, setProducts] = useState<ProductListItem[]>([]); const [cart, setCart] = useState<Array<{ variantId: string; label: string; cantidad: number; precio: number }>>([]); useEffect(() => { api.products.list().then((r) => { if (r.ok) setProducts(r.data); }); }, []); const variants = products.flatMap((p) => p.variants.map((v) => ({ ...v, label: `${p.nombre} ${v.nombre}` }))); async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const v = variants.find((x) => x.id === String(f.get('variantId'))); const cantidad = Number(f.get('cantidad')); if (!v || cantidad <= 0) return; setCart([...cart, { variantId: v.id, label: v.label, cantidad, precio: Number(v.precio) }]); } async function confirm() { const r = await api.orders.create({ userId: user.id, items: cart.map((i) => ({ variantId: i.variantId, cantidad: i.cantidad })) }); if (r.ok) { setCart([]); setNotice({ kind: 'ok', text: `Pedido ${r.data.id} creado` }); } else setNotice({ kind: 'error', text: r.error }); } const total = cart.reduce((s, i) => s + i.precio * i.cantidad, 0); return <Panel title="Ventas"><form onSubmit={add} className="grid gap-3 rounded-xl bg-slate-800 p-4 md:grid-cols-3"><select name="variantId" className="input">{variants.map((v) => <option key={v.id} value={v.id}>{v.label} · {money(v.precio)} · stock {v.stock}</option>)}</select><input name="cantidad" className="input" type="number" min="1" defaultValue="1" /><button className="btn-primary">Agregar al carrito</button></form><Table headers={['Item', 'Cantidad', 'Subtotal']} rows={cart.map((i) => [i.label, i.cantidad, money(i.precio * i.cantidad)])} /><div className="mt-4 flex items-center justify-between"><b>Total: {money(total)}</b><button disabled={!cart.length} onClick={confirm} className="btn-primary disabled:opacity-50">Confirmar pedido</button></div></Panel>; }

function Orders({ user, setNotice }: { user: UserSession; setNotice: (n: Notice) => void }) { const [orders, setOrders] = useState<OrderListItem[]>([]); const [cash, setCash] = useState<CashRegisterSummary | null>(null); const load = async () => { const [or, ca] = await Promise.all([api.orders.list(user), api.cash.current()]); if (or.ok) setOrders(or.data); else setNotice({ kind: 'error', text: or.error }); if (ca.ok) setCash(ca.data); }; useEffect(() => { void load(); }, []); async function update(orderId: string, estado: OrderStatus, paymentMethod?: PaymentMethod) { const r = await api.orders.updateStatus({ orderId, estado, userId: user.id, cashRegisterId: cash?.id, paymentMethod }); if (r.ok) { setNotice({ kind: 'ok', text: estado === 'PAGADO' ? 'Pedido cobrado correctamente' : 'Estado actualizado' }); await load(); } else setNotice({ kind: 'error', text: r.error }); } return <Panel title="Pedidos"><Table headers={['Pedido', 'Items', 'Total', 'Estado', 'Acciones']} rows={orders.map((o) => [o.id.slice(-6), o.items.map((i) => `${i.producto} ${i.variante} x${i.cantidad}`).join('\n'), money(o.total), o.estado, <div className="flex flex-wrap gap-2"><select defaultValue={o.estado} onChange={(e) => void update(o.id, e.target.value as OrderStatus)} className="input">{statuses.filter((s) => s !== 'PAGADO').map((s) => <option key={s}>{s}</option>)}</select><button onClick={() => void update(o.id, 'PAGADO', 'EFECTIVO')} className="btn-primary">Cobrar efectivo</button><button onClick={() => void update(o.id, 'PAGADO', 'TARJETA')} className="btn-muted">Tarjeta</button><button onClick={() => void update(o.id, 'PAGADO', 'YAPE_PLIN')} className="btn-muted">Yape/Plin</button></div>])} /></Panel>; }

function Cash({ user, setNotice }: { user: UserSession; setNotice: (n: Notice) => void }) { const [cash, setCash] = useState<CashRegisterSummary | null>(null); const load = async () => { const r = await api.cash.current(); if (r.ok) setCash(r.data); else setNotice({ kind: 'error', text: r.error }); }; useEffect(() => { void load(); }, []); async function open(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await api.cash.open({ userId: user.id, initialAmount: String(f.get('initialAmount')) }); if (r.ok) { setCash(r.data); setNotice({ kind: 'ok', text: 'Caja abierta' }); } else setNotice({ kind: 'error', text: r.error }); } async function movement(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!cash) return; const f = new FormData(e.currentTarget); const r = await api.cash.registerMovement({ cashRegisterId: cash.id, userId: user.id, tipo: String(f.get('tipo')) as any, monto: String(f.get('monto')), detalle: { nota: String(f.get('nota')) } }); if (r.ok) { setCash(r.data); setNotice({ kind: 'ok', text: 'Movimiento registrado' }); } else setNotice({ kind: 'error', text: r.error }); } async function close() { if (!cash) return; const r = await api.cash.close({ cashRegisterId: cash.id, userId: user.id }); if (r.ok) { setCash(null); setNotice({ kind: 'ok', text: 'Caja cerrada' }); } else setNotice({ kind: 'error', text: r.error }); } return <Panel title="Caja">{!cash ? <form onSubmit={open} className="flex gap-3"><input name="initialAmount" className="input" type="number" step="0.01" defaultValue="100.00" /><button className="btn-primary">Abrir caja</button></form> : <><div className="grid gap-4 md:grid-cols-3"><Metric title="Estado" value={cash.status} /><Metric title="Monto inicial" value={money(cash.initialAmount)} /><Metric title="Saldo actual" value={money(cash.balance)} /></div><form onSubmit={movement} className="mt-4 grid gap-3 rounded-xl bg-slate-800 p-4 md:grid-cols-4"><select name="tipo" className="input"><option>GASTO</option><option>RETIRO</option><option>DEPOSITO</option></select><input name="monto" className="input" type="number" step="0.01" min="0.01" /><input name="nota" className="input" placeholder="Detalle" /><button className="btn-primary">Registrar</button></form><button onClick={close} className="btn-danger mt-4">Cerrar caja</button><Table headers={['Tipo', 'Monto', 'Fecha']} rows={cash.movements.map((m) => [m.tipo, money(m.monto), new Date(m.createdAt).toLocaleString()])} /></>}</Panel>; }

function Users({ user, setNotice }: { user: UserSession; setNotice: (n: Notice) => void }) { const [users, setUsers] = useState<UserSummary[]>([]); const load = async () => { const r = await api.users.list(user.id); if (r.ok) setUsers(r.data); else setNotice({ kind: 'error', text: r.error }); }; useEffect(() => { void load(); }, []); async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await api.users.create({ actorId: user.id, nombre: String(f.get('nombre')), pin: String(f.get('pin')), rol: String(f.get('rol')) as UserRole }); if (r.ok) { e.currentTarget.reset(); setNotice({ kind: 'ok', text: 'Usuario creado' }); await load(); } else setNotice({ kind: 'error', text: r.error }); } async function toggle(u: UserSummary) { const r = await api.users.update({ actorId: user.id, id: u.id, activo: !u.activo }); if (r.ok) await load(); else setNotice({ kind: 'error', text: r.error }); } return <Panel title="Usuarios"><form onSubmit={create} className="grid gap-3 rounded-xl bg-slate-800 p-4 md:grid-cols-4"><input name="nombre" className="input" placeholder="Nombre" /><input name="pin" type="password" className="input" placeholder="PIN" /><select name="rol" className="input">{roles.map((r) => <option key={r}>{r}</option>)}</select><button className="btn-primary">Crear usuario</button></form><Table headers={['Nombre', 'Rol', 'Activo', '']} rows={users.map((u) => [u.nombre, u.rol, u.activo ? 'Sí' : 'No', <button onClick={() => void toggle(u)} className="btn-muted">{u.activo ? 'Desactivar' : 'Activar'}</button>])} /></Panel>; }
function Audit({ user }: { user: UserSession }) { const [logs, setLogs] = useState<AuditLogItem[]>([]); const [error, setError] = useState(''); useEffect(() => { api.audit.list(user.id).then((r) => r.ok ? setLogs(r.data) : setError(r.error)); }, [user.id]); return <Panel title="Auditoría">{error && <p className="text-red-300">{error}</p>}<Table headers={['Usuario', 'Acción', 'Fecha', 'Detalle']} rows={logs.map((l) => [l.userName, l.accion, new Date(l.createdAt).toLocaleString(), JSON.stringify(l.detalle)])} /></Panel>; }
function Settings({ db, setDb }: { db: { connected: boolean; message: string }; setDb: (d: { connected: boolean; message: string }) => void }) { const [config, setConfig] = useState<unknown>(null); useEffect(() => { api.config.getPublic().then((r) => { if (r.ok) setConfig(r.data); }); }, []); return <Panel title="Configuración"><pre className="rounded bg-slate-800 p-4">{JSON.stringify(config, null, 2)}</pre><p className={db.connected ? 'text-emerald-300' : 'text-red-300'}>{db.message}</p><button onClick={() => void checkDb(setDb)} className="btn-primary mt-3">Probar conexión</button></Panel>; }

function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl bg-slate-900 p-4 shadow-xl"><h2 className="mb-4 text-xl font-bold">{title}</h2>{children}</section>; }
function Table({ headers, rows }: { headers: string[]; rows: React.ReactNode[][] }) { return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] border-separate border-spacing-y-2 text-sm"><thead><tr>{headers.map((h) => <th key={h} className="px-3 py-2 text-left text-slate-400">{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r, i) => <tr key={i} className="bg-slate-800">{r.map((c, j) => <td key={j} className="whitespace-pre-wrap px-3 py-3 first:rounded-l-lg last:rounded-r-lg">{c}</td>)}</tr>) : <tr><td colSpan={headers.length} className="rounded bg-slate-800 p-4 text-slate-400">Sin registros</td></tr>}</tbody></table></div>; }
